name: Kaigrealms
version: 0.3.8
main: net.ddns.Kaigrealms.Kaigrealms
commands:
  spawn:
    description: Teleports the player to spawn
    usage: /spawn
    permission: Kaig.spawn
    permission-message: You can't go to spawn
  setspawn:
    description: Sets the spawn of the current world
    usage: /setspawn
    permission: Kaig.setspawn
    permission-message: You can't set the world spawn
  suicide:
    description: Kills the player
    usage: /suicide
    permission: Kaig.suicide
    permission-message: You aren't allowed to kill yourself. Should be default, right?
  tpt:
    description: Sends a request to teleport to another player
    usage: /tpt playername
    permission: Kaig.tp
    permission-message: You aren't allowed to teleport to someone
  tph:
    description: Sends a request to another player to teleport to the sender
    usage: /tph playername
    permission: Kaig.tp
    permission-message: You aren't allowed to teleport someone to you
  tpyes:
    description: Accepts a teleport request from a player
    usage: /tpyes playername
    permission: Kaig.tp
    permission-message: You aren't allowed to teleport
  tpno:
    description: Declines a teleport request from a player
    usage: /tpno playername
    permission: Kaig.tp
    permission-message: You aren't allowed to teleport
  fly:
    description: Toggles flight on or off, regardless of gamemode
    usage: /fly
    permission: Kaig.fly
    permission-message: You aren't allowed to fly
  sethome:
    description: Lets a player set a home at a point in that world
    usage: /sethome homename
    permission: Kaig.homes
    permission-message: You aren't allowed to set homes
  home:
    description: Lets a player teleport to their home in its world
    usage: /home homename
    permission: Kaig.homes
    permission-message: You aren't allowed to set homes
permissions:
  Kaigrealms.spawn:
    description: Lets a player teleport to spawn
    default: true
  Kaigrealms.setspawn:
    description: Lets a player set the world spawn
    default: op
  Kaigrealms.suicide:
    description: Lets a player kill themselves
    default: true
  Kaigrealms.tp:
    description: Lets a player teleport
    default: true
  Kaigrealms.fly:
    description: Lets a player fly
    default: true
  Kaigrealms.homes:
    description: Lets a player set homes
    default: true