name: Kaigrealms
version: 0.4.0
main: net.ddns.Kaigrealms.Kaigrealms
commands:
  spawn:
    description: Teleports the player to spawn
    usage: /spawn
    permissions: Kaigrealms.default
    permission-message: You're borked.
  setspawn:
    description: Sets the spawn of the current world
    usage: /setspawn
    permission: Kaig.setspawn
    permission-message: You can't set the world spawn
  suicide:
    description: Kills the player
    usage: /suicide
    permissions: Kaigrealms.default
    permission-message: You're borked.
  tpt:
    description: Sends a request to teleport to another player
    usage: /tpt playername
    permissions: Kaigrealms.default
    permission-message: You're borked.
  tph:
    description: Sends a request to another player to teleport to the sender
    usage: /tph playername
    permissions: Kaigrealms.default
    permission-message: You're borked.
  tpyes:
    description: Accepts a teleport request from a player
    usage: /tpyes playername
    permissions: Kaigrealms.default
    permission-message: You're borked.
  tpno:
    description: Declines a teleport request from a player
    usage: /tpno playername
    permissions: Kaigrealms.default
    permission-message: You're borked.
  getaway:
    description: Takes a player away to a random spot in the world.
    usage: /getaway
    permissions: Kaigrealms.default
    permission-message: You're borked.
  fly:
    description: Toggles flight on or off, regardless of gamemode
    usage: /fly
    permission: Kaig.fly
    permission-message: You aren't allowed to fly
  sethome:
    description: Lets a player set a home at a point in that world
    usage: /sethome homename
  home:
    description: Lets a player teleport to their home in its world
    usage: /home homename
    permissions: Kaigrealms.default
    permission-message: You're borked.
permissions:
  Kaigrealms.default:
    description: Default permissions of a player
    default: true
  Kaigrealms.setspawn:
    description: Lets a player set the world spawn
    default: op